name: Build and test

on:
  pull_request:
  push:
    tags:
    - '*'
    branches:
    - main

# disable concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # ubuntu-latest, macos-13, macos-14, windows-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Boost
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew upgrade
        brew install boost
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libboost-dev
    - name: Install Boost
      if: runner.os == 'Windows'
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
        boost_version: 1.73.0
      env:
        BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}

    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.9'

    - name: Install required Python packages
      run: python3 -m pip install numpy mypy pytest

    # - name: configure
    #   run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5

    # - name: build
    #   if: runner.os != 'Windows'
    #   run: cd build && make

    # - if: runner.os == 'Windows'
    #   run: cd build && cmake --build "."

    - name: Install
      run: |
        pip install --verbose .

    - name: run test
      run: pytest test/test.py
