name: Test Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.9'

    - name: install python packages
      run: python -m pip install numpy mypy pytest

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: build
      run: cd build && cmake --build "."

    - name: run test
      run: python test/test.py
