# Adapted from potpourri3d
name: Test Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      
    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.9'

    - name: install python packages
      run: python3 -m pip install numpy mypy pytest

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)") ..

    - name: build
      run: cd build && make

    - name: run test
      run: python3 test/test.py
